### ISSUE TITLE
header guard

### ISSUE THREAD

**Issue by sparsecoder** [rudaoshi/gpumatrix#1]
In file included from gpumatrix/include/gpumatrix/Matrix.h:780:
In file included from gpumatrix/include/gpumatrix/impl/Implement.h:6:
gpumatrix/include/gpumatrix/impl/EvalImpl.h:1:9: warning: 'EVAL_IMPL_H' is used as a header guard here, followed by
      #define of a different macro [-Wheader-guard]
# ifndef EVAL_IMPL_H

```
    ^~~~~~~~~~~
```

gpumatrix/include/gpumatrix/impl/EvalImpl.h:2:9: note: 'EVAL_INPL_H' is defined here; did you mean 'EVAL_IMPL_H'?
# define EVAL_INPL_H

```
    ^~~~~~~~~~~
    EVAL_IMPL_H
```

N should be M.

**Comment by rudaoshi** [comment]
Thank you. The problem has been fixed in the newest commit.
