### ISSUE TITLE
‘::isnan’ has not been declared

### ISSUE THREAD

**Issue by TianBo-Timothy** [rudaoshi/gpumatrix#2]
When making the project I noticed an error:

/gpumatrix/include/gpumatrix/Functional.h:73:31: error: ‘::isnan’ has not been declared

According to https://stackoverflow.com/a/39133379/2761195, it is due to that \<cmath\> adds #undef to the c functions so that ::isnan become invisible. I cannot find a simple solution to get around of this issue, so can you please provide a fix?

**Comment by rudaoshi** [comment]
What is your programming environment?  I just compile the project with gcc 4.8.3 but no error reported.

**Comment by rudaoshi** [comment]
I've move these functions into std namespace. Please check whether it is OK in your environment.

**Comment by TianBo-Timothy** [comment]
Thanks! It is fixed. 
BTW: my gcc version is 5.4.0.
