### ISSUE TITLE
compile without boost

### ISSUE THREAD

**Issue by TianBo-Timothy** [rudaoshi/gpumatrix#3]
I just run into another compile issue: the library requires boost to compile.

I checked the code. There is only one place where boost is used: in MapArray.h, BOOST_STATIC_ASSERT is used to check the condition D == 1. I tried to replace it with static_assert, it then compiles.

My suggestion is to remove header #include <boost/static_assert.hpp> and replace BOOST_STATIC_ASSERT with static_assert to avoid unnecessary dependency.

**Comment by rudaoshi** [comment]
Boost dependency has been removed. static_assert in C++11 is used instead.

The compiler options for gcc and nvcc are both updated to C++11.
