### ISSUE TITLE
eigen include path

### ISSUE THREAD

**Issue by TianBo-Timothy** [rudaoshi/gpumatrix#4]
Currently the include path for eigen is fixed in test/CMakeLists.txt as follows

INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/include /usr/local/include/eigen3)

Unfortunately in my case, eigen is installed in /usr/include/eigen so that I have to manually change it accordingly. Do you think it is better to provide a cmake option to change the path, or even better use FindEigen3.cmake script to find it?

**Comment by rudaoshi** [comment]
I've add an environment variable for Eigen3 :  EIGEN3_INCLUDE_DIR
You can use it with 

> export EIGEN3_INCLUDE_DIR="..."

or

> cmake -D EIGEN3_INCLUDE_DIR="..." 

FindEigen3.cmake is not friendly to those who do not familiar with cmake or Eigen3 installation.
