### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by TianBo-Timothy** [rudaoshi/gpumatrix#5]
After running test/testGPUMatrix, I get result with a few errors. All errors are related with MatrixVectorAlgebraTest. The error messages are listed as follows:

> MatrixVectorAlgebraTest: .11044
[2=F]47386.8
[3=F]..6.49218e+10
[6=F]
UnaryOperationTest: ..testGPUMatrix: /usr/include/eigen/Eigen/src/Core/util/XprHelper.h:110: Eigen::internal::variable_if_dynamic<T, Value>::variable_if_dynamic(T) [with T = long int; int Value = 1]: Assertion `v == T(Value)' failed.
Aborted

My gcc version is 5.4.0, eigen version is 3.3.4, cuda version is 9.1.

When running ccmake, it shows CUDA_SDK_ROOT_DIR  as CUDA_SDK_ROOT_DIR-NOTFOUND. But it compiles despite this error. I am not sure if it is related.

Please have a look.

**Comment by rudaoshi** [comment]
The problem resides in UnaryOperationTest and has been fixed.  

Not the test runs without error in my environments.
